export const FETCH_TMDB = 'FETCH_TMDB';
export const FETCH_TMDB_SUCCESS = 'FETCH_TMDB_SUCCESS';
export const FETCH_TMDB_FAILED = 'FETCH_TMDB_FAILED';

export const FETCH_TMDB_ID = 'FETCH_TMDB_ID';
export const FETCH_TMDB_ID_SUCCESS = 'FETCH_TMDB_ID_SUCCESS';
export const FETCH_TMDB_ID_FAILED = 'FETCH_TMDB_ID_FAILED';

export const FETCH_OMDB_ID = 'FETCH_OMDB_ID';
export const FETCH_OMDB_ID_SUCCESS = 'FETCH_OMDB_ID_SUCCESS';
export const FETCH_OMDB_ID_FAILED = 'FETCH_OMDB_ID_FAILED';

export const FETCH_YOUTUBE_TRAILER = 'FETCH_YOUTUBE_TRAILER';
export const FETCH_YOUTUBE_TRAILER_SUCCESS = 'FETCH_YOUTUBE_TRAILER_SUCCESS';
export const FETCH_YOUTUBE_TRAILER_FAILED = 'FETCH_YOUTUBE_TRAILER_FAILED';

export const FETCH_IMDB_RATINGS = 'FETCH_IMDB_RATINGS';
export const FETCH_IMDB_RATINGS_SUCCESS = 'FETCH_IMDB_RATINGS_SUCCESS';
export const FETCH_IMDB_RATINGS_FAILED = 'FETCH_IMDB_RATINGS_FAILED';

export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS';
export const FETCH_NOW_PLAYING_FAILED = 'FETCH_NOW_PLAYING_FAILED';

export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILED = 'FETCH_POPULAR_FAILED';

export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';
export const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
export const FETCH_TOP_RATED_FAILED = 'FETCH_TOP_RATED_FAILED';

export const FETCH_UPCOMING = 'FETCH_UPCOMING';
export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS';
export const FETCH_UPCOMING_FAILED = 'FETCH_UPCOMING_FAILED';

export const FETCH_SIMILAR = 'FETCH_SIMILAR';
export const FETCH_SIMILAR_SUCCESS = 'FETCH_SIMILAR_SUCCESS';
export const FETCH_SIMILAR_FAILED = 'FETCH_SIMILAR_FAILED';

export const FETCH_RECENTLY_VIEWED = 'FETCH_RECENTLY_VIEWED';
export const FETCH_RECENTLY_VIEWED_SUCCESS = 'FETCH_RECENTLY_VIEWED_SUCCESS';
export const FETCH_RECENTLY_VIEWED_FAILED = 'FETCH_RECENTLY_VIEWED_FAILED';

export const POST_MOVIE_VIEW = 'POST_MOVIE_VIEW';
export const POST_MOVIE_VIEW_SUCCESS = 'POST_MOVIE_VIEW_SUCCESS';
export const POST_MOVIE_VIEW_FAILED = 'POST_MOVIE_VIEW_FAILED';
